name: dovBearAssignment

on:
  push:
    # branches:
    #   - 'release/v*.*'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    if: "!startsWith(github.event.head_commit.message, '#NORUN')"
    steps:
     - name: Checkout
       uses: actions/checkout@v3
    
     - name: Node.js Setup
       uses: actions/setup-node@v3
       with:
        node-version: 16

     - name: Install Railway
       run: npm i -g @railway/cli

     - name: deploy 
       run: railway up
       env:
        RAILWAY_TOKEN: ${{ secrets.DOVBEARTOKEN }}

     - name: Send Github Action trigger data to Slack
       id: Slack
       uses: slackapi/slack-github-action@v1.23.0
       env:
        SLACK_WEBHOOK_URL: ${{ secrets.TESTSUBMISSION }}
       with:
          status: ${{ job.status}}
          fields: |
            Name: Shin Kaung Pyae Shan 
            Matriculation Number: E1114084
            Email: e1114084@u.nus.edu
            Repository: ${{ github.event.repository.html_url }}
            Deployment URL: https://${{ secrets.RAILWAYBEARLINK }}.up.railway.app/
          custom: |
            {
            "blocks":[
              "accessory":{
               "type": "button",
               "text": {
                 "type": "plain-text",
                 "text": "Go"
                 },
                 "url":"https://${{ secrets.RAILWAYBEARLINK}}.up.railway.app/",
                 "style": "primary"
             
            }
            }
            ]
            }
            
            
            
            



        
     

